name: "Continuous Integration"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  ci:
    name: "Coding Standards"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Run clang-format"
        run: |
          clang-format --verbose -i --style=file $(find ./src | grep -E ".*(\.c|\.h)$")
      - name: "Check Changes"
        run: |
          if [[ $(git diff --name-only | wc -l) == 0 ]]
          then
          exit 0;
          fi
      - name: "Perform Updates"
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com 
          git add $(git diff --name-only)
          git commit -m "Fix Coding Standards"
          git push

